# -*- coding: utf-8 -*-
"""ml_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTJgTM3MqB2e_0JFbxvweDt1OpgD0H_O
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.preprocessing import StandardScaler
from sqlalchemy import create_engine
import pickle, os

#!pip install pymysql
engine = create_engine('mysql+pymysql://root:rsayush13@localhost:3306/ecommerce_intelligence')

# Load the monthly feature
df = pd.read_csv('data/monthly_features.csv', parse_dates=['month'])
print(f"Loaded {len(df)} months of data")

# Feature selection
X = df[['orders_count', 'unique_customers', 'total_freight', 'avg_order_value']]
y = df['actual_revenue']

# Time Based train-test-split
split_idx = len(df) - 3  # Last 3 months data for test
X_train      = X.iloc[:split_idx]
X_test       = X.iloc[split_idx:]
y_train      = y.iloc[:split_idx]
y_test       = y.iloc[split_idx:]
months_test  = df['month'].iloc[split_idx:]

print(f"Training on {len(X_train)} months | Testing on {len(X_test)} months")

plt.scatter(X_train['total_freight'], y_train)
plt.xlabel('Total Freight')
plt.ylabel('Actual Revenue')

# Scale Features
scaler       = StandardScaler()
X_train_sc   = scaler.fit_transform(X_train)  # fit on train only — learn mean/std
X_test_sc    = scaler.transform(X_test)        # apply same scale to test (no re-fitting)

# Train the model - since the pattern of data is linear we going to use LinearRegression
model = LinearRegression()
model.fit(X_train_sc, y_train)

# Performance evalution
y_pred_train = model.predict(X_train_sc)
y_pred_test  = model.predict(X_test_sc)

print("\nModel Performance")
print(f"Train R2 Score: {r2_score(y_train, y_pred_train):.4f}")
print(f"Test R2 Score: {r2_score(y_test, y_pred_test):.4f}")
print(f"Test MAE: R${mean_absolute_error(y_test, y_pred_test):.2f}")   #shows avg error in actual currency

model.coef_

plt.scatter(X_train['total_freight'], y_train)
plt.plot(X_train['total_freight'], y_pred_train, color='red')
plt.xlabel('Total Freight')
plt.ylabel('Actual Revenue')

print("\nFeature Importance")
for feat, coef in zip(X, model.coef_):
  print(f" {feat:<25}: {coef:+.2f}")
print(f"  {'Intercept':<25}: {model.intercept_:+.2f}")
# Positive coef = feature increases revenue when it goes up
# Negative coef = feature decreases revenue (rare but possible with freight)

# Predictions for 3 months forecast
# A - For test set (actual revene is known)
results_df = pd.DataFrame({
    'month':              months_test.values,
    # Include all features that were part of X_test
    'orders_count':       X_test['orders_count'].values,
    'unique_customers':   X_test['unique_customers'].values,
    'total_freight':      X_test['total_freight'].values,
    'predicted_revenue':  y_pred_test.round(2),
    'actual_revenue':     y_test.values
})

# B - Future 3 months forecast (actual revene is unknown)
# We assume 3% monthly growth rate
last_features = X.iloc[-1].values.reshape(1, -1) # This contains [orders_count, unique_customers, total_freight, avg_order_value]
future_months = pd.date_range(df['month'].max(), periods=4, freq='ME')[1:]

future_rows = []
current = last_features.copy()
for month in future_months:
  current = current * 1.03   # apply 3% growth each month to all 4 features
  scaled = scaler.transform(current)
  pred = model.predict(scaled)[0]
  future_rows.append({
        'month':              month,
        # Assign values from current array to the correct feature names
        'orders_count':       int(current[0][0]),
        'unique_customers':   int(current[0][1]),
        'total_freight':      int(current[0][2]),
        'predicted_revenue':  round(pred, 2),
        'actual_revenue':     None    # unknown — this is the forecast
  })

  future_df = pd.DataFrame(future_rows)

# Combine historical test predictions + future forecast
all_predictions = pd.concat([results_df, future_df], ignore_index=True)

# Save to MySQL predictions table
all_predictions.to_sql('predictions', engine, if_exists='replace', index=False)
print(f"\n Saved {len(all_predictions)} rows to predictions table")
print("   (includes 3-month future forecast with NULL actual_revenue)")

# Save model to disk
os.makedirs('models', exist_ok=True)
with open('models/revenue_model.pkl', 'wb') as f:
    pickle.dump(model, f)
with open('models/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print(" Model saved to models/")